onmessage = function () {
	postMessage({'orders':[],'consoleMessage':"Bonjour,",'error':''});
	postMessage({'orders':[],'consoleMessage':"Je n'ai l'air de rien...",'error':''});
	postMessage({'orders':[],'consoleMessage':"Mais vous allez être surpris par ma botte secrète !",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
	postMessage({'orders':[],'consoleMessage':"...",'error':''});
};
