if(typeof exports === 'undefined') exports = this;
exports.onmessage = function () {
	exports.postMessage({'orders':[],'consoleMessage':"Bonjour,",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"Je n'ai l'air de rien...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"Mais vous allez être surpris par ma botte secrète !",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
	exports.postMessage({'orders':[],'consoleMessage':"...",'error':''});
};
